import os


INVERTER_EFFICIENCY = 0.9
SOLAR_SYSTEM_EFFICIENCY = 0.86
DCDC_CHARGING_VOLTAGE = 14.4
DCDC_CHARGING_EFFICIENCY = 0.9
MONTH_DAYS = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
DUTY_FRACTION_MAX = 1.0
DUTY_PERCENT_SCALE = 100.0
MIN_DEVICE_WATTS = 1.0
CSV_FILE = "power_audit.csv"
DEFAULT_OPENAI_MODEL = "gpt-4.1-mini"
OPENAI_MODEL = os.getenv("OPENAI_MODEL", DEFAULT_OPENAI_MODEL)
OPENAI_FALLBACK_MODEL = "gpt-4.1-mini"
OPENAI_API_KEY_ENV_VAR = "OPENAI_API_KEY"
OPENAI_CLIENT_TIMEOUT_SECONDS = 20.0
MAX_AI_INPUT_FIELD_LENGTH = 4000


def get_openai_api_key():
    """Read the OpenAI API key from the environment at runtime."""
    return os.getenv(OPENAI_API_KEY_ENV_VAR)
